In [1]:
import pandas as pd
import numpy as np
import requests
import xgboost as xgb
import os
from dotenv import load_dotenv

load_dotenv(dotenv_path='../.env', override=True)

True

In [2]:
class OceanForecastGenerator:
    """
    Retrieves and processes forecast data to predict future underwater visibility.
    Output column names are designed to match the historical OceanDataGenerator.
    """

    def __init__(self):
        self.noaa_wind_station = "9410230" 
        self.owm_api_key = os.getenv("OWM_API_KEY")
        self.lat, self.lon = 32.8328, -117.2713
        
        self.WAVE_FORECAST_URL = f"https://marine-api.open-meteo.com/v1/marine?latitude={self.lat}&longitude={self.lon}&hourly=wave_height,wave_period,wave_direction"
        self.WEATHER_FORECAST_URL = f"https://api.openweathermap.org/data/3.0/onecall?lat={self.lat}&lon={self.lon}&exclude=current,minutely,hourly,alerts&appid={self.owm_api_key}&units=metric"
        self.TIDE_FORECAST_URL = f"https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?station={self.noaa_wind_station}&product=predictions&datum=mllw&units=metric&time_zone=lst_ldt&format=json"

    def fetch_wave_forecast(self):
        """Fetches wave forecast and matches historical wave column names."""
        res = requests.get(self.WAVE_FORECAST_URL).json()
        
        dates = pd.to_datetime(res['hourly']['time'])
        df = pd.DataFrame({
            'waveHs': res['hourly']['wave_height'],
            'waveTp': res['hourly']['wave_period'],
            'waveDp': res['hourly']['wave_direction']
        }, index=dates)
        
        rads = np.deg2rad(df['waveDp'])
        df['waveDp_sine'] = np.sin(rads)
        df['waveDp_cos'] = np.cos(rads)
        df['wave_steepness'] = df['waveHs'] / df['waveTp']
        df['swell_energy'] = (df['waveHs']**2) * df['waveTp']
        
        wave_agg = df.resample('D').agg({
            'waveHs': ['max', 'mean'], 
            'waveTp': 'mean',
            'wave_steepness': 'mean',
            'swell_energy': 'mean',
            'waveDp_sine': 'mean', 
            'waveDp_cos': 'mean'
        })
        wave_agg.columns = ['_'.join(col).strip() for col in wave_agg.columns.values]
        return wave_agg

    def fetch_weather_forecast(self):
        """Fetches wind and rain forecast and formats them for the model."""
        res = requests.get(self.WEATHER_FORECAST_URL).json()
        
        if 'daily' not in res:
            print(f"OpenWeather API error: {res.get('message', res)}")
            return pd.DataFrame()

        daily_data = []
        for day in res.get('daily', []):
            dt = pd.to_datetime(day['dt'], unit='s')
            daily_data.append({
                'time': dt,
                'wind_speed': day.get('wind_speed', 0),
                'wind_gust': day.get('wind_gust', 0),
                'wind_deg': day.get('wind_deg', 0),
                'rain_mm': day.get('rain', 0)
            })
            
        df = pd.DataFrame(daily_data).set_index('time')
        df['wind_x'] = np.cos(np.radians(df['wind_deg']))
        df['wind_y'] = np.sin(np.radians(df['wind_deg']))
        df['wind_dir_mean'] = np.degrees(np.arctan2(df['wind_y'], df['wind_x'])) % 360
        
        # Full 72h weighting requires historical rain data unavailable from forecast APIs.
        # Using single-day rain as an approximation.
        df['rain_72h_weighted_mm'] = df['rain_mm']
        
        return df[['wind_speed', 'wind_gust', 'wind_dir_mean', 'rain_72h_weighted_mm']]

    def fetch_tide_forecast(self, days=3):
        """Fetches tidal predictions from NOAA."""
        start_date = pd.Timestamp.now().normalize()
        end_date = start_date + pd.Timedelta(days=days)
        
        url = self.TIDE_FORECAST_URL + f"&begin_date={start_date.strftime('%Y%m%d')}&end_date={end_date.strftime('%Y%m%d')}"
        res = requests.get(url, timeout=15).json()
        
        df = pd.DataFrame(res['predictions'])
        df['t'] = pd.to_datetime(df['t'])
        df.set_index('t', inplace=True)
        df['v'] = pd.to_numeric(df['v'])
        
        daily = df.resample('D').agg({'v': ['max', 'mean']})
        daily.columns = ['tide_max', 'tide_mean']
        return daily

    def run_forecast(self):
        """Joins all forecast features into a single dataframe."""
        df_wave = self.fetch_wave_forecast()
        df_weather = self.fetch_weather_forecast()
        df_tide = self.fetch_tide_forecast()
        
        for d in [df_wave, df_weather, df_tide]:
            d.index = pd.to_datetime(d.index).normalize().tz_localize(None)
            
        final_df = df_wave.join(df_weather, how='inner').join(df_tide, how='inner')
        
        day_of_year = pd.to_datetime(final_df.index).dayofyear
        final_df['season_sine'] = np.sin(2 * np.pi * day_of_year / 365.25)
        final_df['season_cos'] = np.cos(2 * np.pi * day_of_year / 365.25)
        
        return final_df
    
    def save_forecast(self, df, filename="forecast_data.parquet"):
        """Saves the forecast dataframe to the data directory."""
        save_path = os.path.join("..", "data", filename)
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        df.to_parquet(save_path, engine="fastparquet")
        print(f"Forecast saved to {save_path} with {len(df)} records.")

In [3]:
ofg = OceanForecastGenerator()
forecast_df = ofg.run_forecast()
ofg.save_forecast(forecast_df)

Forecast saved to ..\data\forecast_data.parquet with 3 records.

In [4]:
class OceanInference:
    """
    Loads a saved XGBoost model and a forecast parquet file to predict 
    upcoming dive conditions. Supports Regressors, Binary, and Multi-class models.
    """
    def __init__(self, model_path="cove_model.json", forecast_path="../data/forecast_data.parquet", model_type="regressor"):
        self.model_path = model_path
        self.forecast_path = forecast_path
        self.model_type = model_type.lower()
        
        self.class_names = ['Poor', 'Fair', 'Good', 'Excellent']
        
        if self.model_type in ["binary", "classifier"]:
            self.model = xgb.XGBClassifier() 
        else:
            self.model = xgb.XGBRegressor()

    def run_predictions(self, threshold=15):
        """
        Loads data, aligns features, and outputs a human-readable forecast.
        
        Args:
            threshold (float): For a Regressor, the visibility in feet needed for a 'Go'.
                               For Binary, the probability (e.g., 0.4) needed for a 'Go'.
                               Ignored for multi-class classifier mode.
        """
        if not os.path.exists(self.model_path):
            print(f"Error: Could not find the model file at {self.model_path}")
            return
            
        self.model.load_model(self.model_path)
        
        if not os.path.exists(self.forecast_path):
            print(f"Error: Could not find the forecast data at {self.forecast_path}")
            return
            
        forecast_df = pd.read_parquet(self.forecast_path)
        
        expected_cols = self.model.get_booster().feature_names
        missing_cols = [col for col in expected_cols if col not in forecast_df.columns]
        
        if missing_cols:
            # Some training features can't be computed from forecast APIs:
            # - SST and peak PSD require a live physical buoy (CDIP realtime only)
            # - Lag and swell trend features require historical lookback unavailable at forecast time
            # These are set to 0 as a known limitation. Retraining on forecast-compatible
            # features only would eliminate this gap.
            print(f"Note: {len(missing_cols)} hindcast-only features (SST, PSD, lags) set to 0 — unavailable from forecast APIs.")
            for col in missing_cols:
                forecast_df[col] = 0
                
        X_predict = forecast_df[expected_cols]
        
        if self.model_type == "regressor":
            predictions = self.model.predict(X_predict)
            binary_preds = (predictions >= threshold).astype(int)
            
            results = pd.DataFrame({
                'Date': forecast_df.index,
                'Predicted_Vis_ft': np.round(predictions, 1),
                'Condition': ['Go' if p == 1 else 'No-Go' for p in binary_preds]
            })
            
        elif self.model_type == "binary":
            probabilities = self.model.predict_proba(X_predict)[:, 1]
            binary_preds = (probabilities >= threshold).astype(int)
            
            results = pd.DataFrame({
                'Date': forecast_df.index,
                'Go_Probability': np.round(probabilities, 3),
                'Condition': ['Go' if p == 1 else 'No-Go' for p in binary_preds]
            })
            
        elif self.model_type == "classifier":
            predictions = self.model.predict(X_predict)
            conditions = [self.class_names[p] for p in predictions]
            
            results = pd.DataFrame({
                'Date': forecast_df.index,
                'Forecasted_Condition': conditions
            })
            
        else:
            print("Error: model_type must be 'regressor', 'binary', or 'classifier'")
            return
        
        results.reset_index(drop=True, inplace=True)
        results['Date'] = results['Date'].dt.strftime('%A, %b %d')
        
        return results

In [5]:
inference = OceanInference(model_path = "../data/regression_cove_model.json", forecast_path = "../data/forecast_data.parquet",model_type='regressor')

In [6]:
inference.run_predictions()

Note: 21 hindcast-only features (SST, PSD, lags) set to 0 — unavailable from forecast APIs.

               Date  Predicted_Vis_ft Condition
0  Thursday, May 14               8.7     No-Go
1    Friday, May 15               9.4     No-Go
2  Saturday, May 16               8.6     No-Go

In [7]:
inference = OceanInference(model_path = "../data/fourClass_cove_model.json", forecast_path = "../data/forecast_data.parquet",model_type='classifier')

In [8]:
inference.run_predictions()

Note: 21 hindcast-only features (SST, PSD, lags) set to 0 — unavailable from forecast APIs.

               Date Forecasted_Condition
0  Thursday, May 14                 Good
1    Friday, May 15                 Good
2  Saturday, May 16                 Good

In [9]:
inference = OceanInference(model_path = "../data/binary_cove_model.json", forecast_path = "../data/forecast_data.parquet",model_type='binary')

In [10]:
inference.run_predictions()

Note: 21 hindcast-only features (SST, PSD, lags) set to 0 — unavailable from forecast APIs.

               Date  Go_Probability Condition
0  Thursday, May 14           0.187     No-Go
1    Friday, May 15           0.187     No-Go
2  Saturday, May 16           0.209     No-Go